<?php
$this->headTitle('Карточка квартиры');
?>


<h1>ЖК <?= $this->residentialName()->render($flat->getResId()) ?> квартира №<?=$flat->getId();?></h1>
<div class="row">
    <div class="col-md-4">
        <a class="btn btn-default" href="/flats/edit/<?=$flat->getId();?>">
            <span class="glyphicon glyphicon-pencil"></span> Редактировать
        </a>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($flat->getId()) ?></td>
            </tr>
            <tr>
                <th>ID во внешней системе:</th>
                <td><?= $this->escapeHtml($flat->getExId()) ?></td>
            </tr>
            <tr>
                <th>Жк:</th>
                <td><?= $this->residentialName()->render($flat->getResId()) ?></td>
            </tr>
            <tr>
                <th>Корпус:</th>
                <td><?= $this->houseNumber()->render($flat->getHouse()) ?></td>
            </tr>
            <tr>
                <th>Этаж:</th>
                <td><?= $this->escapeHtml($flat->getFloor()) ?></td>
            </tr>
            <tr>
                <th>Секция:</th>
                <td><?= $this->escapeHtml($flat->getSection()) ?></td>
            </tr>
            <tr>
                <th>Номер:</th>
                <td><?= $this->escapeHtml($flat->getNumber()) ?></td>
            </tr>
            <tr>
                <th>Кол-во комнат:</th>
                <td><?= $this->escapeHtml($flat->getSizeTxt()) ?></td>
            </tr>
            <tr>
                <th>Площадь:</th>
                <td><?= $this->escapeHtml($flat->getSquare()) ?></td>
            </tr>
            <tr>
                <th>Цена:</th>
                <td><?= $this->escapeHtml($flat->getPrice()) ?></td>
            </tr>
        </table>
    </div>
</div>
