<?php
$this->headTitle('Вход в панель менеджера');


$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email адрес',
    'required' => true,
    'autofocus' => true
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Пароль',
    'required' => true,
    ]);
?>

<div class="row">
    <div class="col-md-12" style="text-align: center;"><h2 style=" font-weight: 900;">Вход в панель управления</h2></div>
</div>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form class="form-horizontal" method="post">
            <?php if ($isLoginError): ?>
            <div class="alert alert-warning" role="alert">
                Неправильный логин или пароль.
                <a href="<?= $this->url('reset-password') ?>">Забыли пароль?</a>
            </div>
            <?php endif; ?>

            <div class="form-group">
                <div class="col-sm-2">
                    <?= $this->formLabel($form->get('email')); ?>
                </div>
                <div class="col-sm-10">
                    <?= $this->formElement($form->get('email')); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-2">
                    <?= $this->formLabel($form->get('password')); ?>
                </div>
                <div class="col-sm-10">
                    <?= $this->formElement($form->get('password')); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div class="checkbox">
                        <label>
                            <?= $this->formElement($form->get('remember_me')); ?> Запомнить меня
                        </label>
                    </div>
                </div>
            </div>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-sign">Войти</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row"></div>