<?php
$this->headTitle('Добавить видео');

$form->get('res_id')->setAttributes([
    'class'=>'form-control',
    'id' => 'res_id'
]);

$form->get('tittle')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'tittle'
]);

$form->get('link')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'link'
]);

$form->get('date')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'date'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h1>Добавить видео</h1>

<p>
    Пожалуйста заполните следующую форму и нажмите кнопку <i>Добавить</i>.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('res_id')); ?>
            <?= $this->formElement($form->get('res_id')); ?>
            <?= $this->formElementErrors($form->get('res_id')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('tittle')); ?>
            <?= $this->formElement($form->get('tittle')); ?>
            <?= $this->formElementErrors($form->get('tittle')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('link')); ?>
            <?= $this->formElement($form->get('link')); ?>
            <?= $this->formElementErrors($form->get('link')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('date')); ?>
            <?= $this->formElement($form->get('date')); ?>
            <?= $this->formElementErrors($form->get('date')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

