<?php
$this->headTitle('Спасибо');
?>

<div class="row">
<div class="col-md-offset-4 col-md-5">
<h1>Восстановить пароль</h1>

<?php if ($id=='sent'): ?>
<p>
    Ссылка для изменения пароля была отправлена на Ваш email адрес.
</p>
<?php elseif ($id=='invalid-email'): ?>
<p>
    Менеджер с таким email не зарегистрирован в системе.
</p>
<?php elseif ($id=='set'): ?>
<p>
    Новый пароль успешно установлен!
</p>
<p>
    Вернуться на <a href="<?= $this->url('login'); ?>">страницу входа</a>.
</p>
<?php elseif ($id=='failed'): ?>

    Ссылка для изменения пароля устарела. Пожалуйста вернитесь
    <a href="<?= $this->url('reset-password') ?>">сюда</a> и попробуйте сбросить Ваш пароль еще раз.
</p>
<?php endif; ?>
</div>
</div>    