<?php
$this->headTitle('Восстановить пароль');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email адрес'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
    ]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2>Восстановить пароль</h2>

        <p>Для восстановления пароля пожалуйста введите Ваш email адрес в поле ниже</p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>                              

        <?= $this->formElement($form->get('captcha')); ?>
        <p class="hint">Введите буквы/цифры выше так, как Вы их видите.</p>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
