<?php
$this->headTitle('Изменить информацию о ЖК');

$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Name'
]);

$form->get('tittle')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Tittle'
]);

$form->get('description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Description',
    'rows' => 4
]);

$form->get('metro')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Metro',
     'list' => 'metroList'
]);

$form->get('region')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Район',
    'list' => 'regionList'
]);

$form->get('address')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Address'
]);

$form->get('housing')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'House count'
]);

$form->get('total_flat')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Total flat'
]);

$form->get('state')->setAttributes([
    'class'=>'form-control',
]);

$form->get('tittle1')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'tittle1'
]);

$form->get('description1')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'description1'
]);

$form->get('complex1')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'complex1'
]);

$form->get('tittle2')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'tittle2'
]);

$form->get('description2')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'description2'
]);

$form->get('complex2')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'complex2'
]);

$form->get('tittle3')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'tittle3'
]);

$form->get('description3')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'description3'
]);

$form->get('complex3')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'complex3'
]);

$form->get('complex')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'complex'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h1>Редактировать ЖК</h1>

<p>
    Пожалуйста заполните следующую форму и нажмите кнопку <i>Добавить</i>.
</p>

<div class="row">
    <?= $this->form()->openTag($form); ?>

    <div class="col-md-6">

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('link')); ?>
            <?= $this->formElement($form->get('link')); ?>
            <?= $this->formElementErrors($form->get('link')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('tittle')); ?>
            <?= $this->formElement($form->get('tittle')); ?>
            <?= $this->formElementErrors($form->get('tittle')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('metro')); ?>
            <?= $this->formElement($form->get('metro')); ?>
            <?= $this->formElementErrors($form->get('metro')); ?>
            <datalist id="metroList">
                <option>Автово </option>
                <option>Адмиралтейская </option>
                <option>Академическая </option>
                <option>Балтийская </option>
                <option>Бухарестская </option>
                <option>Василеостровская </option>
                <option>Владимирская </option>
                <option>Волковская </option>
                <option>Выборгская </option>
                <option>Горьковская </option>
                <option>Гостиный двор </option>
                <option>Гражданский проспект </option>
                <option>Девяткино </option>
                <option>Достоевская </option>
                <option>Елизаровская </option>
                <option>Звёздная </option>
                <option>Звенигородская </option>
                <option>Кировский завод </option>
                <option>Комендантский проспект</option>
                <option>Крестовский остров </option>
                <option>Купчино </option>
                <option>Ладожская </option>
                <option>Ленинский проспект </option>
                <option>Лесная </option>
                <option>Лиговский проспект </option>
                <option>Ломоносовская </option>
                <option>Маяковская </option>
                <option>Международная </option>
                <option>Московская </option>
                <option>Московские ворота </option>
                <option>Нарвская </option>
                <option>Невский проспект </option>
                <option>Новочеркасская </option>
                <option>Обводный канал </option>
                <option>Обухово </option>
                <option>Озерки </option>
                <option>Парк Победы </option>
                <option>Парнас </option>
                <option>Петроградская </option>
                <option>Пионерская </option>
                <option>Площадь Александра Невского 1 </option>
                <option>Площадь Александра Невского 2 </option>
                <option>Площадь Восстания </option>
                <option>Площадь Ленина </option>
                <option>Площадь Мужества </option>
                <option>Политехническая </option>
                <option>Приморская </option>
                <option>Пролетарская </option>
                <option>Проспект Большевиков </option>
                <option>Проспект Ветеранов </option>
                <option>Проспект Просвещения </option>
                <option>Пушкинская </option>
                <option>Рыбацкое </option>
                <option>Садовая </option>
                <option>Сенная площадь </option>
                <option>Спасская </option>
                <option>Спортивная </option>
                <option>Старая Деревня </option>
                <option>Технологический институт 1 </option>
                <option>Технологический институт 2 </option>
                <option>Удельная </option>
                <option>Улица Дыбенко </option>
                <option>Фрунзенская </option>
                <option>Чёрная речка </option>
                <option>Чернышевская </option>
                <option>Чкаловская </option>
                <option>Электросила
            </datalist>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('region')); ?>
            <?= $this->formElement($form->get('region')); ?>
            <?= $this->formElementErrors($form->get('region')); ?>
            <datalist id="regionList">
                <option>Адмиралтейский </option>
                <option>Василеостровский </option>
                <option>Выборгский</option>
                <option>Калининский </option>
                <option>Кировский </option>
                <option>Колпинский </option>
                <option>Красногвардейский </option>
                <option>Красносельский</option>
                <option>Кронштадтский </option>
                <option>Курортный </option>
                <option>Московский </option>
                <option>Невский </option>
                <option>Петроградский </option>
                <option>Петродворцовый </option>
                <option>Приморский</option>
                <option>Пушкинский </option>
                <option>Фрунзенский </option>
                <option>Центральный</option>
            </datalist>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('address')); ?>
            <?= $this->formElement($form->get('address')); ?>
            <?= $this->formElementErrors($form->get('address')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('housing')); ?>
            <?= $this->formElement($form->get('housing')); ?>
            <?= $this->formElementErrors($form->get('housing')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('total_flat')); ?>
            <?= $this->formElement($form->get('total_flat')); ?>
            <?= $this->formElementErrors($form->get('total_flat')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('state')); ?>
            <?= $this->formElement($form->get('state')); ?>
            <?= $this->formElementErrors($form->get('state')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('complex')); ?>
            <?= $this->formElement($form->get('complex')); ?>
            <?= $this->formElementErrors($form->get('complex')); ?>
        </div>

    </div>

    <div class="col-md-6">

        <div class="form-group">
            <?= $this->formLabel($form->get('tittle1')); ?>
            <?= $this->formElement($form->get('tittle1')); ?>
            <?= $this->formElementErrors($form->get('tittle1')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description1')); ?>
            <?= $this->formElement($form->get('description1')); ?>
            <?= $this->formElementErrors($form->get('description1')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('complex1')); ?>
            <?= $this->formElement($form->get('complex1')); ?>
            <?= $this->formElementErrors($form->get('complex1')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('tittle2')); ?>
            <?= $this->formElement($form->get('tittle2')); ?>
            <?= $this->formElementErrors($form->get('tittle2')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description2')); ?>
            <?= $this->formElement($form->get('description2')); ?>
            <?= $this->formElementErrors($form->get('description2')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('complex2')); ?>
            <?= $this->formElement($form->get('complex2')); ?>
            <?= $this->formElementErrors($form->get('complex2')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('tittle3')); ?>
            <?= $this->formElement($form->get('tittle3')); ?>
            <?= $this->formElementErrors($form->get('tittle3')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description3')); ?>
            <?= $this->formElement($form->get('description3')); ?>
            <?= $this->formElementErrors($form->get('description3')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('complex3')); ?>
            <?= $this->formElement($form->get('complex3')); ?>
            <?= $this->formElementErrors($form->get('complex3')); ?>
        </div>

    </div>

    <?= $this->formElement($form->get('submit')); ?>

    <?= $this->form()->closeTag(); ?>
</div>

