<?php
$this->headTitle('Карточка квартиры');

$this->mainMenu()->setActiveItemId('flats');

$this->pageBreadcrumbs()->setItems([
            'Главная'=>$this->url('home'),
            'Квартиры'=>$this->url('flats'),
            'Карточка квартиры'=>$this->url('flats', ['action'=>'view', 'id'=>$flat->getId()])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>Карточка квартиры</h1>
<div class="row">
    <div class="col-md-4">
        <a class="btn btn-default" href="/flats/edit/<?=$flat->getId();?>">
            <span class="glyphicon glyphicon-pencil"></span> Редактировать
        </a>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Жк:</th>
                <td><?= $flat->getResidentialAsString() ?></th>
            </tr>
            <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($flat->getId()) ?></th>
            </tr>
            <tr>
              <th>Номер квартиры:</th>
              <td><?= $this->escapeHtml($flat->getFlatNo()) ?></th>
            </tr>
            <tr>
              <th>Корпус:</th>
              <td><?= $this->escapeHtml($flat->getHousing()) ?></th>
            </tr>
            <tr>
              <th>Секция:</th>
              <td><?= $this->escapeHtml($flat->getSection()) ?></th>
            </tr>
            <tr>
                <th>Количество комнат:</th>
                <td><?=$this->flatSize()->render($flat->getSize());?></th>
            </tr>
            <tr>
              <th>Этаж:</th>
              <td><?= $this->escapeHtml($flat->getFloor()) ?></th>
            </tr>
            <tr>
              <th>Этажность:</th>
              <td><?= $this->escapeHtml($flat->getFloorm()) ?></th>
            </tr>
            <tr>
              <th>Год сдачи дома:</th>
              <td><?= $this->escapeHtml($flat->getYear()) ?></th>
            </tr>
            <tr>
              <th>Жилая площадь:</th>
              <td><?= $this->escapeHtml($flat->getResidentalSquare()) ?></th>
            </tr>
            <tr>
              <th>Общая площадь:</th>
              <td><?= $this->escapeHtml($flat->getTotalSquare()) ?></th>
            </tr>
            <tr>
              <th>Площадь кухни:</th>
              <td><?= $this->escapeHtml($flat->getKitchenSquare()) ?></th>
            </tr>
            <tr>
              <th>Площадь ванной комнаты:</th>
              <td><?= $this->escapeHtml($flat->getBathSquare()) ?></th>
            </tr>
            <tr>
              <th>Площадь холла:</th>
              <td><?= $this->escapeHtml($flat->getHallSquare()) ?></th>
            </tr>
            <tr>
              <th>Площадь балкона:</th>
              <td><?= $this->escapeHtml($flat->getBalconySquare()) ?></th>
            </tr>
            <tr>
              <th>Площадь комнат:</th>
              <td><?= $this->escapeHtml($flat->getRoomsSquare()) ?></th>
            </tr>
            <tr>
              <th>Отделка:</th>
              <td><?= $this->escapeHtml($flat->getIsDecorationAsString()) ?></th>
            </tr>
            <tr>
              <th>Стоимость:</th>
              <td>
                <?= $this->escapeHtml($flat->getPrice()) ?> &#8381;
                <?php if (!is_null($flat->getClient())) { ?>
                  (оплачено: <?=$total;?> &#8381;)
                <?php } ?>
              </th>
            </tr>
            <tr>
              <th>Статус:</th>
              <td><?= $this->escapeHtml($flat->getStateAsString()) ?></th>
            </tr>
            <tr>
              <th>Забронирован до:</th>
              <td><?= $this->escapeHtml($flat->getDateReserved()) ?></th>
            </tr>
            <tr>
              <th>Дата регистрации договора:</th>
              <td><?= $this->escapeHtml($flat->getDateRegistration()) ?></th>
            </tr>
            <tr>
              <th>Клиент:</th>
              <td><?= $this->clientName()->render($flat->getClient()); ?></th>
            </tr>
        </table>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-5">
        <div class="row">
            <div class="apart-view-img" style="background-image: url('/data/flats/<?=$flat->getId();?>/2d.jpeg');"></div>
            <div class="apart-view-img" style="background-image: url('/data/flats/<?=$flat->getId();?>/etag.jpeg');"></div>
        </div>
    </div>
</div>

<!--<h1>Планировки</h1>
  <img src="/data/flats/<?=$flat->getId();?>/3d.jpeg"></img>
  <img src="/data/flats/<?=$flat->getId();?>/2d.jpeg"></img>
  <img src="/data/flats/<?=$flat->getId();?>/etag.jpeg"></img>-->


<?php if (!is_null($flat->getClient())) { ?>
<hr>
<a class="btn btn-default" href="
    <?= $this->url('payments', ['action'=>'add', 'id'=>$flat->getId()]); ?>">
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Добавить платеж
</a>

<h1>Платежи клиента</h1>

<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Время</th>
    <th>Сумма</th>
    <th>Способ оплаты</th>
    <th>Действия</th>
  </tr>
    <?php foreach ($payments as $payment): ?>
      <tr>
        <td><?= $this->escapeHtml($payment->getId()); ?></td>
        <td><?= $this->escapeHtml($payment->getPaymentTime()); ?></a></td>
        <td><?= $this->escapeHtml($payment->getAmount()); ?> &#8381;</a></td>
        <td><?= $this->escapeHtml($payment->getPaymentTypeAsString()); ?></a></td>
        <td>
          <a class="btn btn-default" href="<?= $this->url('payments',
                    ['action'=>'edit', 'id'=>$payment->getId()]); ?>">
            <span class="glyphicon glyphicon-pencil" ></span> Редактировать
          </a>
          <a class="btn btn-default" href="<?= $this->url('payments',
                      ['action'=>'remove', 'id'=>$payment->getId()]); ?>"  onclick="return confirm('Вы уверены?')">
              <span class="glyphicon glyphicon-remove"></span> Удалить
          </a>
        </td>
      </tr>
    <?php endforeach; ?>
</table>

<hr>

<h1>Скачать договор</h1>

<?php if (strlen($error)>0) { ?>
  <div class="alert alert-danger">
    <strong>Внимание!</strong> <?php echo $error; ?>
  </div>
<?php } ?>

<form method="POST" name="template_download_form" id="template_download_form">
  <div class="form-group">
    <select class="form-control" name="template_name">
      <?php foreach($templates as $template): ?>
        <option value='<?=$template;?>'><?=$template;?></option>
      <?php endforeach; ?>
    </select>
    * Вы можете использовать следующие переменные в шаблоне договора:
    <?php
      $keys = array_keys($template_values);
      foreach($keys as $key) echo "[[$key]] ";
    ?>
  </div>
  <input type="submit" name="download_contract" class="btn btn-primary" value="Скачать">
</form>


<?php } ?>