<?php
$this->headTitle('Карточка ЖК');
?>


<h1>Карточка ЖК</h1>
<div class="row">
    <div class="col-md-4">
        <a class="btn btn-default" href="/resident/edit/<?=$resident->getId();?>">
            <span class="glyphicon glyphicon-pencil"></span> Редактировать
        </a>
        <a href="/mapping/add?res_id=<?=$resident->getId();?>";>Добавить карту</a>
        <a href="/housing/add?res_id=<?=$resident->getId();?>";>Добавить корпус</a>
        <a href="/video/add?res_id=<?=$resident->getId();?>";>Добавить видео</a>
        <a href="/resident/parse/<?=$resident->getId();?>";>Обновить квартиры по фиду</a>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($resident->getId()) ?></td>
            </tr>
            <tr>
                <th>Жк:</th>
                <td><?= $resident->getName() ?></td>
            </tr>
            <tr>
                <th>Фид:</th>
                <td><?= $resident->getLink() ?></td>
            </tr>
            <tr>
                <th>Заголовок:</th>
                <td><?= $this->escapeHtml($resident->getTittle()) ?></td>
            </tr>
            <tr>
                <th>Описание:</th>
                <td><?= $this->escapeHtml($resident->getDescription()) ?></td>
            </tr>
            <tr>
                <th>Метро:</th>
                <td><?= $this->escapeHtml($resident->getMetro()) ?></td>
            </tr>
            <tr>
                <th>Адрес:</th>
                <td><?= $this->escapeHtml($resident->getAddress()) ?></td>
            </tr>
            <tr>
              <th>Корпусов:</th>
              <td><?= $this->escapeHtml($resident->getHousing()) ?></td>
            </tr>
            <tr>
                <th>Всего кв:</th>
                <td><?= $this->escapeHtml($resident->getTotalFlat()) ?></td>
            </tr>
            <tr>
              <th>Статус:</th>
              <td><?= $this->escapeHtml($resident->getStateAsString()) ?></td>
            </tr>
        </table>
    </div>
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Заголовок 1:</th>
                <td><?= $this->escapeHtml($resident->getTittle1()) ?></td>
            </tr>
            <tr>
                <th>Описание 1:</th>
                <td><?= $this->escapeHtml($resident->getDescription1()) ?></td>
            </tr>
            <tr>
                <th>Заголовок 2:</th>
                <td><?= $this->escapeHtml($resident->getTittle2()) ?></td>
            </tr>
            <tr>
                <th>Описание 2:</th>
                <td><?= $this->escapeHtml($resident->getDescription2()) ?></td>
            </tr>
            <tr>
                <th>Заголовок 3:</th>
                <td><?= $this->escapeHtml($resident->getTittle3()) ?></td>
            </tr>
            <tr>
                <th>Описание 3:</th>
                <td><?= $this->escapeHtml($resident->getDescription3()) ?></td>
            </tr>
        </table>
        <table class="table table-striped table-bordered">
            <tr>
                <th colspan="2">Корпуса:</th>
            </tr>
            <?php
            foreach($housing as $house){
            ?>
            <tr>
                <th colspan="2">
                    <a href="/housing/view/<?=$this->escapeHtml($house->getId())?>">
                        Корпус №<?=$this->escapeHtml($house->getHouse());?>
                    </a>
                </th>
            </tr>
            <?php } ?>
        </table>
        <table class="table table-striped table-bordered">
            <tr>
                <th colspan="2">Видео:</th>
            </tr>
            <?php
            foreach($videos as $video){
                ?>
                <tr>
                    <th>
                        <a href="/video/edit/<?=$this->escapeHtml($video->getId())?>">
                            <?=$this->escapeHtml($video->getDate());?>
                        </a>
                    </th>
                    <th>
                        <a href="<?=$this->escapeHtml($video->getLink())?>">
                           <?=$this->escapeHtml($video->getLink());?>
                        </a>
                    </th>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>
