<?php
$this->headTitle('Карточка ЖК');
?>


<h1>Карточка ЖК</h1>
<div class="row">
    <div class="col-md-4">
        <a class="btn btn-default" href="/resident/edit/<?=$resident->getId();?>">
            <span class="glyphicon glyphicon-pencil"></span> Редактировать
        </a>
        <a href="/mapping/add?res_id=<?=$resident->getId();?>";>Добавить карту</a>
        <a href="/housing/add?res_id=<?=$resident->getId();?>";>Добавить корпус</a>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($resident->getId()) ?></th>
            </tr>
            <tr>
                <th>Жк:</th>
                <td><?= $resident->getName() ?></th>
            </tr>
            <tr>
                <th>Фид:</th>
                <td><?= $resident->getLink() ?></th>
            </tr>
            <tr>
                <th>Заголовок:</th>
                <td><?= $this->escapeHtml($resident->getTittle()) ?></th>
            </tr>
            <tr>
                <th>Описание:</th>
                <td><?= $this->escapeHtml($resident->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Метро:</th>
                <td><?= $this->escapeHtml($resident->getMetro()) ?></th>
            </tr>
            <tr>
                <th>Адрес:</th>
                <td><?= $this->escapeHtml($resident->getAddress()) ?></th>
            </tr>
            <tr>
              <th>Корпусов:</th>
              <td><?= $this->escapeHtml($resident->getHousing()) ?></th>
            </tr>
            <tr>
                <th>Всего кв:</th>
                <td><?= $this->escapeHtml($resident->getTotalFlat()) ?></th>
            </tr>
            <tr>
              <th>Статус:</th>
              <td><?= $this->escapeHtml($resident->getStateAsString()) ?></th>
            </tr>
        </table>
    </div>
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Заголовок 1:</th>
                <td><?= $this->escapeHtml($resident->getTittle1()) ?></th>
            </tr>
            <tr>
                <th>Описание 1:</th>
                <td><?= $this->escapeHtml($resident->getDescription1()) ?></th>
            </tr>
            <tr>
                <th>Заголовок 2:</th>
                <td><?= $this->escapeHtml($resident->getTittle2()) ?></th>
            </tr>
            <tr>
                <th>Описание 2:</th>
                <td><?= $this->escapeHtml($resident->getDescription2()) ?></th>
            </tr>
            <tr>
                <th>Заголовок 3:</th>
                <td><?= $this->escapeHtml($resident->getTittle3()) ?></th>
            </tr>
            <tr>
                <th>Описание 3:</th>
                <td><?= $this->escapeHtml($resident->getDescription3()) ?></th>
            </tr>
        </table>
        <table class="table table-striped table-bordered">
            <tr>
                <th colspan="2">Корпуса:</th>
            </tr>
            <?php
            foreach($housing as $house){
            ?>
            <tr>
                <th colspan="2">
                    <a href="/housing/view/<?=$this->escapeHtml($house->getId())?>">
                        Корпус №<?=$this->escapeHtml($house->getHouse());?>
                    </a>
                </th>
            </tr>
            <?php } ?>
        </table>
    </div>
</div>
