<?= $this->doctype() ?>
<html lang="en">
<head>
    <?php echo $this->partial('head'); ?>
</head>
<body class="js-loading">
<div id="loader">
    <div id="cube-loader">
        <div class='sk-double-bounce'>
            <div class='sk-child sk-double-bounce-1'></div>
            <div class='sk-child sk-double-bounce-2'></div>
        </div>
    </div>
</div><!--/Loader-->

<div id="main" class="<?= $this->current()->render(); ?>">
    <div id="wrapper">
        <div id="balls">
            <div class="bg-top"></div>
            <div class="bg-bottom"></div>
            <div class="ball ball-1"><img src="img/ball/ball-1.png" alt=""/></div>
            <div class="ball ball-2"><img src="img/ball/ball-2.png" alt=""/></div>
            <div class="ball ball-3"><img src="img/ball/ball-1.png" alt=""/></div>
            <div class="ball ball-4"><img src="img/ball/ball-1.png" alt=""/></div>
        </div>
        <?php echo $this->partial('header'); ?>

        <?= $this->content ?>

    </div><!-- End #wrapper -->
    <?php echo $this->partial('footer'); ?>
</body>
</html>