<?= $this->doctype() ?>
<html lang="en">
<head>
    <?php echo $this->partial('head'); ?>

</head>

<body class="js-loading">
<div id="loader">
    <div id="cube-loader">
        <div class='sk-double-bounce'>
            <div class='sk-child sk-double-bounce-1'></div>
            <div class='sk-child sk-double-bounce-2'></div>
        </div>
    </div>
</div>
<!--/Loader-->

<div id="main" class="<?= $this->current()->render(); ?>">
    <div id="wrapper"><?php echo $this->partial('header'); ?>

        <?= $this->content ?>

    </div><!-- End #wrapper -->
    <?php echo $this->partial('footer'); ?>

    <script type="text/javascript" src="/js/ion.rangeSlider.js"></script>
    <script type="text/javascript" src="/js/rangeSlider.js"></script>
</body>

</html>

