<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('metr-restate')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/old_style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        <script>
            $('#myTabs a').click(function (e) {
                e.preventDefault()
                $(this).tab('show')
            })
        </script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('admin') ?>">Главная</a></li>

                        <li><a href="<?= $this->url('resident') ?>">Список ЖК</a></li>
                        <li><a href="<?= $this->url('mapping') ?>">Список карт</a></li>
                        <li><a href="<?= $this->url('housing') ?>">Корпуса</a></li>
                        <li><a href="<?= $this->url('video') ?>">Видео</a></li>
                        <li><a href="<?= $this->url('mortgage') ?>">Ипотека</a></li>
                        <li><a href="<?= $this->url('anews') ?>">Новости</a></li>
                        <li><a href="<?= $this->url('flats') ?>">Квартиры</a></li>
                        <li><a href="<?= $this->url('commertials') ?>">Помещения</a></li>


                        <li><a href="<?= $this->url('logout') ?>">Выход</a></li>
                    </ul>
            </div>
        </nav>
        <div class="container" style="margin-top: 50px;">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2019               - <?= date('Y') ?> by ATR-MEDIA Ltd. All rights reserved.</p>
            </footer>
        </div>

        <script>
            function confirmDelete(url, id) {
                data = {
                    'id' : id
                }
                $.ajax({
                    type: "POST",
                    url: "/"+url+"/delete",
                    data: data,
                    success: function (msg) {
                        $('#'+url+id).remove();
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        console.log(XMLHttpRequest)
                    }
                });
            }
        </script>
        <?= $this->inlineScript() ?>
    </body>
</html>
