<?php
$this->headTitle('Список заявок');
?>
<h1>Список заявок</h1>

<table class="table table-striped" id="orders-table">

    <tr>
        <th>Id</th>
        <th>Дата</th>
        <th>Имя</th>
        <th>Телефон</th>
        <th></th>
        <th></th>
    </tr>

    <?php foreach ($orders as $order): ?>

        <tr id="orders<?=$order->getId()?>">
            <td>
                <?= $this->escapeHtml($order->getId()); ?>
            </td>
            <td><?= $this->escapeHtml($order->getDate()); ?></a></td>
            <td><?= $this->escapeHtml($order->getName()); ?></a></td>
            <td><?= $this->escapeHtml($order->getPhone()); ?></a></td>
            <td>
                <a class="btn btn-default" href="<?= $this->url('orders',
                    ['action' => 'edit', 'id' => $order->getId()]); ?>">
                    Редактировать
                </a>
            </td>
            <td>
                <a class="btn btn-default" href="#"
                   onclick="return confirm('Вы уверены?') ? confirmDelete('orders', <?= $order->getId() ?>) : false">
                    Удалить
                </a>
            </td>
        </tr>

    <?php endforeach; ?>
</table>


