<?php
$this->headTitle('Карточка корпуса');
?>


<h1>ЖК <?= $this->residentialName()->render($house->getResId()) ?> корпус №<?=$house->getHouse();?></h1>
<div class="row">
    <div class="col-md-4">
        <a class="btn btn-default" href="/housing/edit/<?=$house->getId();?>">
            <span class="glyphicon glyphicon-pencil"></span> Редактировать
        </a>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($house->getId()) ?></td>
            </tr>
            <tr>
                <th>Жк:</th>
                <td><?= $this->residentialName()->render($house->getResId()) ?></td>
            </tr>
            <tr>
                <th>Номер:</th>
                <td><?= $this->escapeHtml($house->getHouse()) ?></td>
            </tr>
            <tr>
                <th>Этажей:</th>
                <td><?= $this->escapeHtml($house->getFloor()) ?></td>
            </tr>
            <tr>
                <th>Секций:</th>
                <td><?= $this->escapeHtml($house->getSection()) ?></td>
            </tr>
            <tr>
                <th>Всего кв:</th>
                <td><?= $this->escapeHtml($house->getTotalFlat()) ?></td>
            </tr>
            <tr>
                <th>Продано кв:</th>
                <td><?= $this->saleFlatCount()->render($house->getResId(), $house->getId()) ?></td>
            </tr>
            <tr>
                <th>Статус строительства:</th>
                <td><?= $this->escapeHtml($house->getStateAsString()) ?></td>
            </tr>
            <tr>
                <th>Продажа:</th>
                <td><?= $this->escapeHtml($house->getSellAsString()) ?></td>
            </tr>
            <tr>
              <th>Год сдачи:</th>
              <td><?= $this->escapeHtml($house->getYear()) ?></td>
            </tr>
        </table>
    </div>
</div>
