<figure class="item fadeEl">
    <div class="img"><img src="/img/product/img-4.jpg" alt="" /></div>
    <figcaption>
        <div class="top-ico">
            <div class="favorites like-com" data-id="<?=$com->getId()?>">
                <svg xmlns="http://www.w3.org/2000/svg" width="13" height="12" viewBox="0 0 13 12">
                    <path class="heart" d="M1078.54,90s-10.3-8.578-5.05-11.384a27.845,27.845,0,0,0,10,0c5.26,2.805-4.95,11.384-4.95,11.384m-0.08-9.344a6.556,6.556,0,0,0-1.06-.869,2.872,2.872,0,0,0-3-.076,1.232,1.232,0,0,0-.74.975,1.977,1.977,0,0,0-.02.248c0,1.891,2.63,4.972,4.9,7.1,2.23-2.117,4.81-5.182,4.81-7.073a2.166,2.166,0,0,0-.01-0.257,1.25,1.25,0,0,0-.76-0.987,2.531,2.531,0,0,0-2.9.008,6.408,6.408,0,0,0-1.22.937" transform="translate(-1072 -78)"></path>
                </svg>
            </div>
            <!--.favorites-->
        </div>
        <!-- .tag -->
        <div class="info">
            <h3>Помещение № <?=$com->getNumber()?> </h3>
            <p>ЖК “<?=$this->residentialName()->render($com->getResId())?>”</p>
            <div class="flex">
                <p><?=$com->getFinishAsString()?></p>
                <p><?=$com->getSquare()?> м2</p>
                <p><?=$com->getFloor()?> этаж</p>
            </div>
            <div class="price">
                <p><?=$this->formatPrice()->render($com->getPrice())?><span>руб.</span></p>
            </div>
        </div>
        <!-- .info -->
    </figcaption>
    <a href="/commertial/view/<?=$com->getId()?>"  onclick="return getAjax('commertial/view/<?=$com->getId()?>');"  class="link"></a>
</figure>