<figure class="item fadeEl">
    <div class="img"><img src="/img/content/no-image.jpeg" alt="" class="smoll-img"/></div>
    <figcaption>
        <div class="tag">
            <div class="tag-value value-1">Квартиры от 3 млн. руб.</div>
            <div class="tag-value value-<?=$house->getStatusNum()?>"><?=$house->getStatus()?></div>
        </div>
        <!-- .tag -->
        <div class="info">
            <h3>ЖК “<?=$this->residentialName()->render($house->getResId())?>”</h3>
            <p>Помещений <?=$this->houseNumber()->getComCount($house->getId())?></p>
            <p>Проданных квартир <?= $this->saleFlatCount()->render($house->getResId(), $house->getId()); ?></p>
            <p>Метро звездное</p>
            <p>Московское шоссе 13б</p>
        </div>
        <!-- .info -->
    </figcaption>
    <a href="/commertial?resident=<?=$house->getResId()?>" class="link"></a>
</figure>