<script type="text/javascript">
    $(document).ready(function() {
        $('#price_min').val(<?=$data['price_min'];?>);
        $('#price_max').val(<?=$data['price_max'];?>);
        $('#square_min').val(<?=$data['square_min'];?>);
        $('#square_max').val(<?=$data['square_max'];?>);
        $('#year').val(<?=$data['year'];?>);
        $('#floor').val(<?=$data['floor'];?>);
        $('#res').val(<?=$data['resident'];?>);

    });
</script>
<ul class="hList">
    <li class="menu_li li_select type-s">
        <div class="tit-choce"><span>Коммерческая недвижимость</span></div>
    </li>
    
    <li class="menu_li li_select size-select" style="display:none;">
        <form method="post" class="form_select" name="form1" id="form1">
            <div>
                <select id="size" multiple="multiple">
                    <option value="0">Студия</option>
                    <option value="1">1 комнатная</option>
                    <option value="2">2 комнатная</option>
                    <option value="3">3 комнатная</option>
                    <option value="4">4 комнатная</option>
                </select>
            </div>
        </form>
        <script>
            var arr = [];
            $(function () {
                $('#size').multiselect({
                    includeSelectAllOption: true,
                    selectAllText: 'Все',
                    allSelectedText: 'Все',
                    nonSelectedText: 'Кол-во комнат'
                });
                <?php
                if(isset($data['size']) && is_array($data['size'])) {
                foreach ($data['size'] as $s){
                ?>
                arr.push(<?=$s;?>);
                <?php } } ?>
                $('#size').multiselect('select', arr);
            });
        </script>
    </li>

    <li class="menu_li li_select no-arrow square-select">
        <form class="form_select">
            <span class="tit">Площадь</span>
            <div>
                <select id="square_min">
                    <option selected class="t-tit" value="">от</option>
                    <option value="1">1 м.</option>
                    <option value="10">10 м.</option>
                    <option value="20">20 м.</option>
                    <option value="30">30 м.</option>
                    <option value="40">40 м.</option>
                    <option value="50">50 м.</option>
                </select>
            </div>
        </form>
        <script>
            $(function() {
                $('#square_min').multiselect({
                    includeSelectAllOption: true
                });
            });
        </script>

        <span class="dash">-</span>

        <form class="form_select">
            <div>
                <select id="square_max">
                    <option selected class="t-tit" value="">до</option>
                    <option value="1">1 м.</option>
                    <option value="10">10 м.</option>
                    <option value="20">20 м.</option>
                    <option value="30">30 м.</option>
                    <option value="40">40 м.</option>
                    <option value="50">50 м.</option>
                </select>
            </div>
        </form>
        <script>
            $(function() {
                $('#square_max').multiselect({
                    includeSelectAllOption: true
                });
            });
        </script>
    </li>

    <li class="menu_li li_select no-arrow">
        <form class="form_select">
            <span class="tit">Цена</span>
            <div>
                <select id="price_min">
                    <option selected class="t-tit" value="">от</option>
                    <option value="0">0 млн.руб.</option>
                    <option value="1000000">1 млн.руб.</option>
                    <option value="1500000">1,5 млн.руб.</option>
                    <option value="2000000">2,0 млн.руб.</option>
                    <option value="2500000">2,5 млн.руб.</option>
                    <option value="3000000">3,0 млн.руб.</option>
                    <option value="3500000">3,5 млн.руб.</option>
                    <option value="4000000">4,0 млн.руб.</option>
                    <option value="4500000">4,5 млн.руб.</option>
                    <option value="5000000">5,0 млн.руб.</option>
                    <option value="5500000">5,5 млн.руб.</option>
                    <option value="6000000">6,0 млн.руб.</option>
                    <option value="6500000">6,5 млн.руб.</option>
                    <option value="7000000">7,0 млн.руб.</option>
                    <option value="7500000">7,5 млн.руб.</option>
                    <option value="8000000">8,0 млн.руб.</option>
                    <option value="8500000">8,5 млн.руб.</option>
                    <option value="9000000">9,0 млн.руб.</option>
                    <option value="9500000">9,5 млн.руб.</option>
                </select>
            </div>
        </form>
        <script>
            $(function() {
                $('#price_min').multiselect({
                    includeSelectAllOption: true
                });
            });
        </script>

        <span class="dash">-</span>

        <form class="form_select">
            <div>
                <select id="price_max">
                    <option selected class="t-tit" value="">до</option>
                    <option value="1000000">1 млн.руб.</option>
                    <option value="1500000">1,5 млн.руб.</option>
                    <option value="2000000">2,0 млн.руб.</option>
                    <option value="2500000">2,5 млн.руб.</option>
                    <option value="3000000">3,0 млн.руб.</option>
                    <option value="3500000">3,5 млн.руб.</option>
                    <option value="4000000">4,0 млн.руб.</option>
                    <option value="4500000">4,5 млн.руб.</option>
                    <option value="5000000">5,0 млн.руб.</option>
                    <option value="5500000">5,5 млн.руб.</option>
                    <option value="6000000">6,0 млн.руб.</option>
                    <option value="6500000">6,5 млн.руб.</option>
                    <option value="7000000">7,0 млн.руб.</option>
                    <option value="7500000">7,5 млн.руб.</option>
                    <option value="8000000">8,0 млн.руб.</option>
                    <option value="8500000">8,5 млн.руб.</option>
                    <option value="9000000">9,0 млн.руб.</option>
                    <option value="9500000">9,5 млн.руб.</option>
                    <option value="10000000">10,0 млн.руб.</option>
                </select>
            </div>
        </form>
        <script>
            $(function() {
                $('#price_max').multiselect({
                    includeSelectAllOption: true
                });
            });
        </script>
    </li>

    <li class="menu_li li_select">
        <form method="post" class="form_select" name="form4">
            <div>
                <select id="metro" multiple="multiple">
                    <?php foreach ($this->filterData()->getmetro() as $metro) { ?>
                        <option value="<?= $metro ?>"><?= $metro ?></option>
                    <?php } ?>
                </select>
            </div>
        </form>
        <script>
            $(function () {
                $('#metro').multiselect({
                    includeSelectAllOption: true,
                    selectAllText: 'Все',
                    allSelectedText: 'Все',
                    nonSelectedText: 'Метро'
                });
                arr = [];
                <?php
                if(isset($data['metro']) && is_array($data['metro'])) {
                foreach ($data['metro'] as $m){
                ?>
                arr.push('<?=$m;?>');
                <?php } } ?>
                $('#metro').multiselect('select', arr);
            });
        </script>
    </li>

    <li class="menu_li li_select">
        <form method="post" class="form_select" name="form5">
            <div>
                <select id="region" multiple="multiple">
                    <?php foreach ($this->filterData()->getRegion() as $region) { ?>
                        <option value="<?= $region ?>"><?= $region ?></option>
                    <?php } ?>
                </select>
            </div>
        </form>
        <script>
            $(function () {
                $('#region').multiselect({
                    includeSelectAllOption: true,
                    selectAllText: 'Все',
                    allSelectedText: 'Все',
                    nonSelectedText: 'Район'
                });
                arr = [];
                <?php
                if(isset($data['region']) && is_array($data['region'])) {
                foreach ($data['region'] as $reg){
                ?>
                arr.push('<?=$reg;?>');
                <?php } } ?>
                $('#region').multiselect('select', arr);
            });
        </script>
    </li>
</ul>

<div class="menu-filter_bottom">
    <div class="flex">
        <div class="l-block">

            <div class="menu_li li_select" style="display:none;">
                <form method="post" class="form_select" name="form6">
                    <div>
                        <select id="floor">
                            <option selected class="t-tit" value="">Этаж</option>
                            <?php for ($i = 1; $i < 18; $i++) { ?>
                                <option value="<?= $i ?>"><?= $i ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </form>
                <script>
                    $(function () {
                        $('#floor').multiselect({
                            includeSelectAllOption: true
                        });
                    });
                </script>
            </div>
            <!-- ITEM -->
            
            <div class="menu_li li_select">
                <form class="form_select">
                    <div>
                        <select id="year">
                            <option selected class="t-tit" value="">Год сдачи</option>
                            <?php
                            $years = $this->filterData()->getYear();
                            foreach ($years as $year){
                                ?>
                                <option value="<?=$year?>"><?=$year?> г.</option>
                            <?php } ?>
                        </select>
                        </select>
                    </div>
                </form>
                <script>
                    $(function() {
                        $('#year').multiselect({
                            includeSelectAllOption: true
                        });
                    });
                </script>
            </div>
            <!-- ITEM -->

            <div class="menu_li li_select">
                <form class="form_select">
                    <div>
                        <select id="res">
                            <option selected class="t-tit" value="">ЖК</option>
                            <?php
                            $residents = $this->filterData()->getResident();
                            foreach ($residents as $key => $res){
                                ?>
                                <option value="<?=$key?>"><?=$res?></option>
                            <?php } ?>
                        </select>
                    </div>
                </form>
                <script>
                    $(function() {
                        $('#res').multiselect({
                            includeSelectAllOption: true
                        });
                    });
                </script>
            </div>
            <!-- ITEM -->
        </div>

        <div class="btn-block">
            <a onclick="sendForm()" class="btn">Подобрать квартиру</a>
        </div>
    </div>
    <!-- flex -->
</div>
<!-- menu-filter_bottom -->

<!--<script>-->
<!--    function sendForm() {-->
<!--        url = '/commertial';-->
<!--        data_Send = {-->
<!--            square_min: $('#square_min').val(),-->
<!--            square_max: $('#square_max').val(),-->
<!--            price_min: $('#price_min').val(),-->
<!--            price_max: $('#price_max').val(),-->
<!--            metro: $('#metro').val(),-->
<!--            region: $('#region').val(),-->
<!--            year: $('#year').val(),-->
<!--            resident: $('#res').val(),-->
<!--        };-->
<!--        var json = JSON.stringify(data_Send);-->
<!--        // console.table(data);-->
<!--        // console.log(json);-->
<!--        $.ajax({-->
<!--            type: "POST",-->
<!--            url: "/commertial",-->
<!--            data: data_Send,-->
<!--            success: function (msg) {-->
<!--                document.location.reload();-->
<!--            },-->
<!--            error: function (XMLHttpRequest, textStatus, errorThrown) {-->
<!--                alert("error");-->
<!--            }-->
<!--        });-->
<!--    }-->
<!--</script>-->

<script>
    function sendForm() {
        $.post("/commertial/ajax-com",
            {
                size: $('#size').val(),
                square_min: $('#square_min').val(),
                square_max: $('#square_max').val(),
                price_min: $('#price_min').val(),
                price_max: $('#price_max').val(),
                floor: $('#floor').val(),
                metro: $('#metro').val(),
                region: $('#region').val(),
                year: $('#year').val(),
                resident: $('#res').val(),
            },
            function (data) {
                $('#ajax_content').html(data);
                // console.log(data);
                $('.fadeEl').each(function () {
                    $(this).addClass('anim');
                });
                $('.js-animation').each(function () {
                    $(this).addClass('start-animation');
                });
            });
    }
</script>