<ul class="hList">
    <li class="menu_li li_select type-s">
        <form  class="form_select type-select">
            <div>
                <select id="type">
                    <option selected disabled class="t-disabled">Тип недвижимости</option>
                    <option class="type-kv" value="flat">Квартиры</option>
                    <option class="type-kom" value="commertial">Коммерческая недвижемость</option>
                </select>
            </div>
        </form>
        <script>
            $(function() {
                $('#type').multiselect({
                    includeSelectAllOption: true
                });


                $(".type-select .multiselect-container>li").click(function(){

                    var typeclass = $(this).attr('class');
                    $("#menu-filter.index-filter").addClass('show');
                    $("#menu-filter.index-filter").attr('type', typeclass);

                })
            });
        </script>
    </li>


    <li class="menu_li li_select room-select">
        <form  class="form_select">
            <div>
                <select id="size" multiple="multiple">
                    <option value="0">Студия</option>
                    <option value="1">1 комнатная</option>
                    <option value="2">2 комнатная</option>
                    <option value="3">3 комнатная</option>
                    <option value="4">4 комнатная</option>
                </select>
            </div>
        </form>
        <script>
            var arr = [];
            $(function() {
                $('#size').multiselect({
                    includeSelectAllOption: true,
                    selectAllText: 'Все',
                    allSelectedText: 'Все',
                    nonSelectedText: 'Кол-во комнат'
                });
                <?php
                if(isset($data['size']) && is_array($data['size'])) {
                foreach ($data['size'] as $s){
                ?>
                arr.push(<?=$s;?>);
                <?php } } ?>
                $('#size').multiselect('select', arr);
            });
        </script>
    </li>

    <li class="menu_li li_select no-arrow square-select">
        <form  class="form_select">
            <span class="tit">Площадь</span>
            <div>
                <select id="square_min_com">
                    <option selected class="t-disabled" value="">от</option>
                    <option value="1">1 м.</option>
                    <option value="10">10 м.</option>
                    <option value="20">20 м.</option>
                    <option value="30">30 м.</option>
                    <option value="40">40 м.</option>
                    <option value="50">50 м.</option>
                </select>
            </div>
        </form>
        <script>
            $(function() {
                $('#square_min_com').multiselect({
                    includeSelectAllOption: true
                });
            });
        </script>

        <span class="dash">-</span>

        <form class="form_select">
            <div>
                <select id="square_max_com">
                    <option selected class="t-disabled" value="">до</option>
                    <option value="1">1 м.</option>
                    <option value="10">10 м.</option>
                    <option value="20">20 м.</option>
                    <option value="30">30 м.</option>
                    <option value="40">40 м.</option>
                    <option value="50">50 м.</option>
                </select>
            </div>
        </form>
        <script>
            $(function() {
                $('#square_max_com').multiselect({
                    includeSelectAllOption: true
                });
            });
        </script>
    </li>

    <li class="menu_li li_select no-arrow price-ov">
        <form  class="form_select">
            <span class="tit">Цена</span>
            <div>
                <select id="price_min">
                    <option selected disabled class="t-disabled">от</option>
                    <option value="0">0 млн.руб.</option>
                    <option value="1000000">1 млн.руб.</option>
                    <option value="1500000">1,5 млн.руб.</option>
                    <option value="2000000">2,0 млн.руб.</option>
                    <option value="2500000">2,5 млн.руб.</option>
                    <option value="3000000">3,0 млн.руб.</option>
                    <option value="3500000">3,5 млн.руб.</option>
                    <option value="4000000">4,0 млн.руб.</option>
                    <option value="4500000">4,5 млн.руб.</option>
                </select>
            </div>
        </form>
        <script>
            $(function() {
                $('#price_min').multiselect({
                    includeSelectAllOption: true
                });
            });
        </script>

        <span class="dash">-</span>

        <form class="form_select">
            <div>
                <select id="price_max">
                    <option selected disabled class="t-disabled">до</option>
                    <option value="1000000">1 млн.руб.</option>
                    <option value="1500000">1,5 млн.руб.</option>
                    <option value="2000000">2,0 млн.руб.</option>
                    <option value="2500000">2,5 млн.руб.</option>
                    <option value="3000000">3,0 млн.руб.</option>
                    <option value="3500000">3,5 млн.руб.</option>
                    <option value="4000000">4,0 млн.руб.</option>
                    <option value="4500000">4,5 млн.руб.</option>
                </select>
            </div>
        </form>
        <script>
            $(function() {
                $('#price_max').multiselect({
                    includeSelectAllOption: true
                });
            });
        </script>
    </li>

    <li class="menu_li li_select">
        <form  class="form_select">
            <div>
                <select id="metro" multiple="multiple">
                    <option>Автово </option>
                    <option>Адмиралтейская </option>
                    <option>Академическая </option>
                    <option>Балтийская </option>
                    <option>Бухарестская </option>
                    <option>Василеостровская </option>
                    <option>Владимирская </option>
                    <option>Волковская </option>
                    <option>Выборгская </option>
                    <option>Горьковская </option>
                    <option>Гостиный двор </option>
                    <option>Гражданский проспект </option>
                    <option>Девяткино </option>
                    <option>Достоевская </option>
                    <option>Елизаровская </option>
                    <option>Звёздная </option>
                    <option>Звенигородская </option>
                    <option>Кировский завод </option>
                    <option>Комендантский проспект</option>
                    <option>Крестовский остров </option>
                    <option>Купчино </option>
                    <option>Ладожская </option>
                    <option>Ленинский проспект </option>
                    <option>Лесная </option>
                    <option>Лиговский проспект </option>
                    <option>Ломоносовская </option>
                    <option>Маяковская </option>
                    <option>Международная </option>
                    <option>Московская </option>
                    <option>Московские ворота </option>
                    <option>Нарвская </option>
                    <option>Невский проспект </option>
                    <option>Новочеркасская </option>
                    <option>Обводный канал </option>
                    <option>Обухово </option>
                    <option>Озерки </option>
                    <option>Парк Победы </option>
                    <option>Парнас </option>
                    <option>Петроградская </option>
                    <option>Пионерская </option>
                    <option>Площадь Александра Невского 1 </option>
                    <option>Площадь Александра Невского 2 </option>
                    <option>Площадь Восстания </option>
                    <option>Площадь Ленина </option>
                    <option>Площадь Мужества </option>
                    <option>Политехническая </option>
                    <option>Приморская </option>
                    <option>Пролетарская </option>
                    <option>Проспект Большевиков </option>
                    <option>Проспект Ветеранов </option>
                    <option>Проспект Просвещения </option>
                    <option>Пушкинская </option>
                    <option>Рыбацкое </option>
                    <option>Садовая </option>
                    <option>Сенная площадь </option>
                    <option>Спасская </option>
                    <option>Спортивная </option>
                    <option>Старая Деревня </option>
                    <option>Технологический институт 1 </option>
                    <option>Технологический институт 2 </option>
                    <option>Удельная </option>
                    <option>Улица Дыбенко </option>
                    <option>Фрунзенская </option>
                    <option>Чёрная речка </option>
                    <option>Чернышевская </option>
                    <option>Чкаловская </option>
                    <option>Электросила</option>
                </select>
            </div>
        </form>
        <script>
            $(function() {
                $('#metro').multiselect({
                    includeSelectAllOption: true,
                    selectAllText: 'Все',
                    allSelectedText: 'Все',
                    nonSelectedText: 'Метро'
                });
            });
        </script>
    </li>

    <li class="menu_li li_select">
        <form  class="form_select">
            <div>
                <select id="region" multiple="multiple">
                    <option>Адмиралтейский </option>
                    <option>Василеостровский </option>
                    <option>Выборгский</option>
                    <option>Калининский </option>
                    <option>Кировский </option>
                    <option>Колпинский </option>
                    <option>Красногвардейский </option>
                    <option>Красносельский</option>
                    <option>Кронштадтский </option>
                    <option>Курортный </option>
                    <option>Московский </option>
                    <option>Невский </option>
                    <option>Петроградский </option>
                    <option>Петродворцовый </option>
                    <option>Приморский</option>
                    <option>Пушкинский </option>
                    <option>Фрунзенский </option>
                    <option>Центральный</option>
                </select>
            </div>
        </form>
        <script>
            $(function() {
                $('#region').multiselect({
                    includeSelectAllOption: true,
                    selectAllText: 'Все',
                    allSelectedText: 'Все',
                    nonSelectedText: 'Район'
                });
            });
        </script>
    </li>


    <li class="b-block">
        <a href="#" onclick="sendForm()" class="btn">Подобрать квартиру</a>
    </li>
</ul>

<script>
    function sendForm() {
        url = '/' + $('#type').val();
        data_Send = {
            size: $('#size').val(),
            price_min: $('#price_min').val(),
            price_max: $('#price_max').val(),
            price_min_com: $('#price_min').val(),
            price_max_com: $('#price_max').val(),
            square_min_com: $('#square_min_com').val(),
            square_max_com: $('#square_max_com').val(),
            metro: $('#metro').val(),
            region: $('#region').val(),
            floor: '',
            year: '',
            resident: '',
            year_com: '',
            resident_com: '',
        };
        var json = JSON.stringify(data_Send);
        // console.table(data);
        // console.log(json);
        $.ajax({
            type: "POST",
            url: url,
            data: data_Send,
            success: function (msg) {
                document.location.href=url;
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert("error");
            }
        });
    }
</script>