<?php
$this->headTitle('Карточка новость');
?>


<h1>Новость <?= $this->escapeHtml($news->getId());?></h1>
<div class="row">
    <div class="col-md-4">
        <a class="btn btn-default" href="/housing/edit/<?=$news->getId();?>">
            <span class="glyphicon glyphicon-pencil"></span> Редактировать
        </a>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($news->getId()) ?></th>
            </tr>
            <tr>
                <th>Жк:</th>
                <td><?= $this->residentialName()->render($news->getResId()) ?></th>
            </tr>
            <tr>
                <th>Заголовок:</th>
                <td><?= $this->escapeHtml($news->getTittle()) ?></th>
            </tr>
            <tr>
                <th>Текст:</th>
                <td><?= $this->escapeHtml($news->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Дата:</th>
                <td><?= $this->escapeHtml($news->getDate()) ?></th>
            </tr>
        </table>
    </div>
</div>
