<?= $this->headTitle('Карта обьектов');?>
<div class="header_middle">
    <div class="main-txt">
        <h1>Карта объектов</h1>
    </div>
</div>
<!-- .header_middle -->
</div>
<!-- End .container -->
</header>
<article class="inside">
    <section id="object-map">
        <span class="metadata-marker" style="display: none;" data-region_tag="html-body"></span>

        <script>
            var map;

            function initMap() {
                var coordinates = {lat: 59.938696, lng: 30.336523},
                    popupContent = '<a href="/" class="content">Что угодно</a>',
                    map = new google.maps.Map(document.getElementById('map'), {
                        center: {lat: 59.938696, lng: 30.336523},
                        zoom: 10
                    });
                <?php
                foreach ($maps as $map) {
                    echo "coordinates{$map->getId()} = {lat: {$map->getX()}, lng: {$map->getY()}},
//             name{$map->getId()}= '<a href=\"/complex/view/{$map->getResId()}\" class=\"content\">{$this->residentialName()->render($map->getResId())}</a>',
             name{$map->getId()}= '<div class=\"map-object\"><div class=\"tit\">ЖК “{$this->residentialName()->render($map->getResId())}”</div><p>Квартиры от 6 млн. руб.</p><p>Свободных квартир {$this->residentialName()->flatCount($map->getResId())}</p><a href=\"/complex/view/{$map->getResId()}\" onclick=\"return getAjax(\'complex\/view\/{$map->getResId()}\')\" class=\"more\">Подробнее</a></div>',
             marker{$map->getId()} = new google.maps.Marker({
                position: coordinates{$map->getId()},
                map: map,
                animation: google.maps.Animation.DROP,
                icon: '/img/ico/map.png'
                });
                infowindow{$map->getId()} = new google.maps.InfoWindow({
                    content: name{$map->getId()}
                });
                marker{$map->getId()}.addListener('click', function(){
                    infowindow{$map->getId()}.open(map, marker{$map->getId()});
                    });\n";
                }
                ?>
                marker = new google.maps.Marker({
                    position: coordinates,
                    map: map,
                    animation: google.maps.Animation.DROP
                });

                infowindow = new google.maps.InfoWindow({
                    content: popupContent
                });
                marker.addListener('click', function () {
                    infowindow.open(map, marker);
                });
            }
        </script>

        <div id="map"></div>
    </section>
</article>