

<div class="header_middle">
    <div class="main-txt">
        <h1>Избранное</h1>
        <p>Квартиры, которые вам понравились</p>
    </div>
</div><!-- .header_middle -->
</div><!-- End .container -->
</header>

<article id="favorites-page" class="inside">
    <section id="product">
        <div class="container">
            <div class="product_block">
                <?php if(isset($flats)){ ?>
                <?php foreach ($flats as $flat){?>
                    <?php echo $this->partial('application/partial/flat_second', ['flat' => $flat]); ?>
                <?php }} else { ?>
                <p>В избранном ничего нет!</p>
                <?php } ?>
            </div><!-- End .product_block -->
        </div><!-- End .container -->
    </section>
    <div id="feedback-modal" class="modal-block btn call_us">Позвоните нам</div>
</article>