<div class="header_middle">
    <div class="main-txt">
        <h1><?php echo str_replace(' ', " <br>", $flat->getSizeTxt())?> № <?=$flat->getNumber()?></h1>
        <div class="flex">
            <a href="/complex/view/<?=$flat->getResId()?>" class="back name">ЖК “<?= $this->residentialName()->render($flat->getResId()) ?>”</a>
            <a href="#" class="back">Вернуться к выбору квартиры</a>
        </div>
    </div>
</div>
<!-- .header_middle -->
</div>
<!-- End .container -->
</header>

<article class="relative">
    <section id="apartment-page" class="product-one">
        <div class="container">
            <div class="product_top">
                <div class="img fadeEl fadeEl-left"><img src="<?=$flat->getPlan()?>" alt="" /></div>
                <div class="txt fadeEl fadeEl-right">
                    <div class="item">
                        <div class="tit">Площадь</div>
                        <p><?=$flat->getSquare()?> м2</p>
                    </div>
                    <div class="item">
                        <div class="tit">Количество комнат</div>
                        <p><?=$flat->getSizeAsString()?></p>
                    </div>
                    <div class="item">
                        <div class="tit">Этаж</div>
                        <p><?=$flat->getFloor()?></p>
                    </div>
                    <div class="item">
                        <div class="tit">Секция</div>
                        <p><?=$flat->getSection()?></p>
                    </div>
                    <div class="item">
                        <div class="tit">Корпус</div>
                        <p><?= $this->houseNumber()->render($flat->getHouse()) ?></p>
                    </div>
                    <div class="item">
                        <div class="tit">Год сдачи</div>
                        <p><?=$flat->getYear()?></p>
                    </div>
                    <div class="item no-margin">
                        <div class="tit">.pdf</div>
                        <a href="#">Скачать</a>
                    </div>
                    <div class="item no-margin">
                        <div class="tit">Поделиться</div>
                        <div class="soc">
                            <a href="#">Вк</a>
                            <a href="#">f</a>
                            <a href="#">ok</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- product_top -->

            <div class="product_bottom fadeEl">
                <div class="l-block">
                    <div id="feedback-modal" class="modal-block btn">Забронировать</div>
                    <div id="video_modal" class="modal-block plan">План этажа</div>
                </div>
                <div class="r-block">
                    <div class="old-price">2 790 000 <span class="size-smoll">руб.</span></div>
                    <div class="price">2 245 000 <span class="size-smoll">руб.</span></div>
                </div>
                <div class="add-block">
                    <a href="#" class="add-f">Добавить в избранное</a>
                    <a href="#" class="c-mortgage">Рассчитать ипотеку</a>
                </div>
            </div>
            <!--product_bottom-->
        </div>
        <!-- End .container -->
    </section>
    <?php echo $this->partial('application/partial/flat_mortgage', ['banks' => $banks]); ?>
</article>
<div class="modal" data-id="#video_modal">
    <div class="modal-ov"></div>
    <div class="modal-content">
        <span class="close  close-v">&times;</span>
        <div class="video-block">
            <img src="<?=$flat->getPlan()?>" alt="" />
        </div>
    </div>
</div>