<?= $this->headTitle('Контакты');?>
<div class="header_middle">
    <div class="main-txt">
        <h1>Контакты</h1>
    </div>
</div>
<!-- .header_middle -->
</div>
<!-- End .container -->
</header>

<article class="inside">
    <section id="contacts-page">
        <div class="flex">
            <div class="contacts-block fadeEl fadeEl-left">
                <p>ООО “Агенство недвижимости <br>МЕТР.restate”</p>
                <p>185014, Петрозаводск, <br>Максима Горького 25, <br>офис 308</p>
                <div id="feedback-modal" class="modal-block btn call_us">Позвоните нам</div>
                <div class="soc">
                    <a href="#">Вк</a>
                    <a href="#">f</a>
                    <a href="#">ok</a>
                </div>
            </div><!--contacts-block-->
            <div id="map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1886.5070452010054!2d34.34661401578245!3d61.7818243190445!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46a1ec48815130a1%3A0xa831fa1d9026b2d8!2z0YPQuy4g0JzQsNC60YHQuNC80LAg0JPQvtGA0YzQutC-0LPQviwgMjUsINCf0LXRgtGA0L7Qt9Cw0LLQvtC00YHQuiwg0KDQtdGB0L8uINCa0LDRgNC10LvQuNGPLCDQoNC-0YHRgdC40Y8sIDE4NTAzNQ!5e0!3m2!1sru!2sby!4v1553014559180" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe></div>
        </div>
    </section>
</article>
</div>