<div class="header_middle">
    <div class="main-txt">
        <h1>Подобрать коммерческое помещение</h1>
    </div>

    <div id="menu-filter" class="fadeEl choce-filter choice-kom-filter">
        <?php echo $this->partial('application/partial/filter_com'); ?>
    </div><!-- #menu-filter -->

</div><!-- .header_middle -->
</div><!-- End .container -->
</header>

<article id="choce-page" class="inside">
    <section id="product">
        <div class="container">
            <div class="title-block js-animation">
                <h2>Помещения по вашим параметрам(<?=$count?>)</h2></div>
            <div class="product_block">
                <?php foreach ($coms as $com){?>
                    <?php echo $this->partial('application/partial/com', ['com' => $com]); ?>
                <?php } ?>
            </div>
            <!-- End .product_block -->
            <div id="feedback-modal" class="modal-block btn call_us">Позвоните нам</div>
            <?= $this->paginationControl($coms,
                'Sliding',
                'application/partial/flat_paginator',
                array('route' => 'commertial', 'fromQuery' => $fromQuery)); ?>
        </div>
        <!-- End .container -->
    </section>
</article>